In [1]:
import  pandas as pd
import matplotlib.pyplot as plt
import  numpy as np
import requests

## <working with Json !!!!!!!!>

In [2]:
df =pd.read_json("train.json")
df

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [3]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')
df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [4]:
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1560520,Batman: Knightfall Part 1: Knightfall,"Arkham Asylum has been destroyed, and all its ...",2026-06-23,39.8177,9.100,475
1,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,67.0473,9.045,1365
2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,47.4998,8.847,2264
3,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,12.4379,8.823,403
4,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...,2025-07-18,50.9890,8.798,2320

In [5]:
df.to_csv('movies1.csv')

In [6]:
df = pd.DataFrame()

In [7]:
df

Empty DataFrame
Columns: []
Index: []

In [8]:
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = df.concat(temp_df,ignore_index=True)

AttributeError: 'DataFrame' object has no attribute 'concat'

In [ ]:
df.to