## api keys

In [4]:
import pandas as pd
import requests

In [5]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')
response

In [6]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [7]:
temp_df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1560520,Batman: Knightfall Part 1: Knightfall,"Arkham Asylum has been destroyed, and all its ...",2026-06-23,39.8177,9.100,475
1,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,67.0473,9.045,1365
2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,47.4998,8.847,2264
3,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,12.4379,8.823,403
4,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...,2025-07-18,50.9890,8.798,2320

In [8]:
df = pd.DataFrame()

In [9]:
df

Empty DataFrame
Columns: []
Index: []

In [13]:
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df.append(temp_df,ignore_index=True)

KeyboardInterrupt:

In [14]:
df

Empty DataFrame
Columns: []
Index: []

In [15]:
df.shape

(0, 0)

In [ ]:
temp_df.to_csv('s.csv')